create table if not exists public.todos (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(trim(title)) > 0),
  completed boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.todos enable row level security;

grant usage on schema public to anon;
grant select, insert, update, delete on public.todos to anon;

-- For a quick local demo through the Java backend, prefer using a service_role key
-- in backend-only environment variables. Do not expose service_role keys to Vue.
--
-- If you want to use the anon key instead, add policies appropriate to your demo:
drop policy if exists "Allow anon read todos" on public.todos;
create policy "Allow anon read todos"
on public.todos
for select
to anon
using (true);

drop policy if exists "Allow anon insert todos" on public.todos;
create policy "Allow anon insert todos"
on public.todos
for insert
to anon
with check (true);

drop policy if exists "Allow anon update todos" on public.todos;
create policy "Allow anon update todos"
on public.todos
for update
to anon
using (true)
with check (true);

drop policy if exists "Allow anon delete todos" on public.todos;
create policy "Allow anon delete todos"
on public.todos
for delete
to anon
using (true);
